### ISSUE TITLE
Functionality to hide the field that gets populated

### ISSUE THREAD

**Issue by aidanoleary** [victorsolaya/Multiselect_Records_PCF#10]
It would be cool to have the option to hide the field that gets populated with the data, for example if you were using it to capture record GUIDs.

**Comment by victorsolaya** [comment]
Many thanks for that enhancement, quite nice, I didn't about it.

I will give it a shot today and I will come back to you.
Many thanks for the effort

**Comment by victorsolaya** [comment]
Just merged the changed into the main repo.

Many thanks for your help! Glad to see you could be using it in your projects!
