### ISSUE TITLE
Release Managed Solution Fails Solution Checker Validation

### ISSUE THREAD

**Issue by aidanoleary** [victorsolaya/Multiselect_Records_PCF#13]
Currently the released managed solution fails the solution checker's validation (https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/use-powerapps-checker). The reason for this is the control needs to be built in release mode (https://docs.microsoft.com/en-us/powerapps/developer/component-framework/import-custom-controls), when it's built in release mode it will prevent the eval js function from being used in the bundle.js file.

**Comment by victorsolaya** [comment]
Good catch!
But, it was a managed solution, how could you run the Power Apps Checker against it?
I am updating the v0.9.53 right now with the Release mode.
Many thanks for this!

**Comment by aidanoleary** [comment]
Good point ;P. We just tend to run the solution checker on all solutions as part of our CI process but yeah to be fair we don't really have to do that on managed solutions.

**Comment by victorsolaya** [comment]
That's quite good actually. I thought you were using the PowerShell in order to run all these managed solutions but it is quite a nightmare to configure tbh :D
I will be closing this issue as I updated the new release with that configuration.
Many thanks for that!
