### ISSUE TITLE
Select all not working

### ISSUE THREAD

**Issue by Fernandobo21** [victorsolaya/Multiselect_Records_PCF#18]
First of all, thanks for creating this PCF, iit's really useful.

I found this issue or bug, only in the last version.
After checking the select all option
![image](https://user-images.githubusercontent.com/4930082/99956654-ac07ec00-2d86-11eb-852a-9d94166d886a.png)

when i click the "select element" button it doesn't select the registries, but if i go one by one it works.
The issue is only with when selecting all the item at the same time.

If it helps, in the previous version this didn't happened.

thanks agains for this solution and feel free to ask me for tests or help.

**Comment by victorsolaya** [comment]
Hey! Thanks for raising the issue. I will check and I will come back to you with a response asap.
Thanks!

**Comment by victorsolaya** [comment]
Hi @Fernandobo21  This has been fixed in the v1.0.0.6.
Let me know if that works for you and if it is, please, close the issue.

Thank you for the feedback!

**Comment by Fernandobo21** [comment]
Checked
Works fine again.

Thanks a lot for solving the issue in a very short time.

**Comment by Fernandobo21** [comment]
Checked
Works fine again.

Thanks a lot for solving the issue in a very short time.
