### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by dim895** [victorsolaya/Multiselect_Records_PCF#20]
Hello, 

This is  a really cool enhancement and thank you a lot!.

 I wanted to know if it would be possible to make a enhacement that could facilitate the reporting (advanced view).

I was thinking the following:
Is it possible to have in the field the values stored with just ; like a regular multiselect? I have all the technical field (Id) which is stored in the field but I only need to have the values.

Please

**Comment by victorsolaya** [comment]
Hi!

Thanks for the feedback! 
However, as I changed this to open the form I would need the ID as well, I can suggest to you two things:
1. You can download the version 0.9.53 that is the one I had before.2
2. Go and download this PCF https://pcf.gallery/multiselect-entity-picker/ Probably that's more what you expect.

Let me know if I can help you with any of those.

Thank you!

**Comment by dim895** [comment]
In fact, yours is much more pretty and better explained. Moreover you have an impressive filter that was not able to reproduce in the other PCF.

I downloaded the previous version you mentionned but faced some bugs that are solved in current version so I will not be able to use.

Do not worry I will use the latest version you implemented

**Comment by victorsolaya** [comment]
Great, thanks for the feedback. 
Do you think a new PCF with the previous version with bugs fixed would be helpful for the community? If so I can work on that.
What are the bugs you found so I can work with them from version 0.9.53?

Thank you!

**Comment by dim895** [comment]
I think it would as many customers want to use advanced views. What i was not able to do with 0.9.53 is that results were not displayed directly, I had to type some letters and then click enter (there is no loop like the latest version

**Comment by victorsolaya** [comment]
Great! Thanks for that! I will create a new PCF so instead of creating tags, the values will be displayed split with the delimiter you want. I will merge the latest features we have for this PCF with the previous one. 
Hopefully that will solve the issue you are having. I will contact you once I create the new PCF if you want through this issue, would you like that?

Thanks!

**Comment by dim895** [comment]
That would BE AWESOME!

**Comment by victorsolaya** [comment]
Great I will work on that, meanwhile, I can suggest to you creating an onChange function so you can take the attribute you are changing with the MultiSelect, and then set the values in another one.
Like:
var multiselectJSON = getAttribute("multiselect").getValue().map( item => item.name)
getAttribute("yourfieldtodisplay").setValue(multiselectJSON)
