### ISSUE TITLE
Enhancement Request: scrolling on lookup

### ISSUE THREAD

**Issue by acehaddock** [victorsolaya/Multiselect_Records_PCF#24]
First of love the PCF :) 

I noticed that there is no Scrolling on the values in the lookup.  you can use arrow keys but there is no native scroll 

would be a great enhancement to have this functionality. #

**Comment by victorsolaya** [comment]
Hi! I will take a look as soon as I have some spare time! Many thanks for raising this issue

**Comment by victorsolaya** [comment]
Hi @acehaddock 

Many thanks for raising this issue. 
I have done some improvements to that so in the release 1.0.0.9 is being done.
This is what you can expect in this release.


https://user-images.githubusercontent.com/11043789/115994023-a6346200-a5d5-11eb-94e1-8305babf48d8.mp4

Thank you!

**Comment by acehaddock** [comment]
Amazing!!! Thanks so much 

Sent from my iPhone
Cole Haddock

**Comment by victorsolaya** [comment]
Great! I will close the issue. Many thanks for the catch!
