### ISSUE TITLE
Issue in CSS of PCF control dropdown

### ISSUE THREAD

**Issue by shivamagarwal10** [victorsolaya/Multiselect_Records_PCF#29]
We have been using “Multiselect_Records_PCF” control in our CRM Application. We have facing a css issue in the control after implementation.

Issue: dropdown background is coming in excess on the screen
Scenario:

User clicked on the search icon in PCF control.
Dropdown css not showing properly.

I have also attached the screenshot for reference. It will be very helpful if you can spare some time to look into it.
<img width="430" alt="PCF CSS Issue" src="https://user-images.githubusercontent.com/83083015/121361381-dbf99400-c952-11eb-979f-6839a2e9c366.PNG">

**Comment by shivamagarwal10** [comment]
Hi Team,

@victorsolaya. Waiting for the response.

**Comment by victorsolaya** [comment]
Hi @shivamagarwal10 

A new version has been released https://github.com/victorsolaya/Multiselect_Records_PCF/releases/tag/v1.0.0.11
This fixes the layout problem

![image](https://user-images.githubusercontent.com/11043789/124794552-70094c00-df4f-11eb-81f2-fefea14722b5.png)

Thank you

**Comment by shivamagarwal10** [comment]
Thank you very much for new release, After importing new release issue has been perfectly resolved. Thankyou very much for your support.
