### ISSUE TITLE
Displaying Multi Tags

### ISSUE THREAD

**Issue by DameshPeri** [victorsolaya/Multiselect_Records_PCF#31]
I am not a techy person, but found the step up relatively simple. Great instructions.

But I have come across a problem. I am able to select multiple fields, but only one of the selection gets displayed. 
Also i noticed that the write back to the field is not comma separated values
<img width="160" alt="image 4" src="https://user-images.githubusercontent.com/87134310/124935071-3727b080-dffd-11eb-839a-2fa4abd2a0b2.PNG">

I am unsure if i am doing something wrong or if there is a bug.

Any guidance would be hugely appreciated. 

<img width="372" alt="image 2" src="https://user-images.githubusercontent.com/87134310/124934076-55d97780-dffc-11eb-9983-542c311cecb1.PNG">
<img width="370" alt="image 3" src="https://user-images.githubusercontent.com/87134310/124934084-56720e00-dffc-11eb-91d4-6904145160fe.PNG">
<img width="418" alt="image 1" src="https://user-images.githubusercontent.com/87134310/124934087-56720e00-dffc-11eb-85f6-9d2791c216f4.PNG">

**Comment by victorsolaya** [comment]
Hi @DameshPeri I am not using comma separated values. I am using a JSON format with Name: "", Id: "". However, I can see your iqd_gradetagid is with uppercase the I. 
I did this solution so you can click in the tag and a form appears.

One of the things you have set probably is stopping the behaviour you want, and it is the Filter Tags. Set that as No.

If you want, there is another solution that only sets the other names
https://github.com/victorsolaya/Multiselect_Records_PCF/tree/refs/tags/v0.9.53

If not, you can use this:
https://pcf.gallery/multiselect-entity-picker/

Let me know how it goes.

Thank you!

**Comment by DameshPeri** [comment]
Hi @victorsolaya, thank you for quick response. 

It was the 'iqd_gradetagid is with uppercase the I'. It now displays like your demo.

I wanted to use the value in a search, hence I was hoping it might be comma separated value. 

https://github.com/victorsolaya/Multiselect_Records_PCF/tree/refs/tags/v0.9.53 - the images don't load.

I really like your work, its taken me ages to find a solution for multiselect. You've done a fab job.

So thanks.

**Comment by victorsolaya** [comment]
Sorry, wrong url:
https://github.com/victorsolaya/Multiselect_Records_PCF/tree/v0.9.53

In this one the images are shown.

Thank you!

**Comment by DameshPeri** [comment]
One final question.

Would you be able to add the UI to v0.9.53, so you get the individual record names showing in the blue boxes?

Thanks

**Comment by victorsolaya** [comment]
That's something I didn't think about, since that's like the old solution.
Probably I will start that at some point as a new project.
However, I don't know when it could be done since this is something I do in my spare time 😓

**Comment by DameshPeri** [comment]
Thanks and i look forward to it 😊
