### ISSUE TITLE
Single Record Select Option

### ISSUE THREAD

**Issue by dapicella** [victorsolaya/Multiselect_Records_PCF#35]
Hey Victor love the pcf control! Is there an option to select a single record instead of multiple? A great use for this is email templates. One cannot create a custom lookup to the email templates table but I can use this pcf control, however, I only want the user to select one email template and not multiple. Thanks!

**Comment by victorsolaya** [comment]
Hi. A new solution has been created including the isMultiple tag.
Try to check it out.

Thank you!
