### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by CamilleFS** [victorsolaya/Multiselect_Records_PCF#38]
i can't seem to figure out if there is a way to 'sort' the selected values, based on a field. so the selected values for example gets sorted desc. when showing in edit form mode? 

i'm not sure if possible, but i also need a way to limit the combox to selections to fields that are not yet selected in another row. is that possible+

thanks for an awesome combox feature :)

**Comment by victorsolaya** [comment]
You can configure it in the fetchxml
