### ISSUE TITLE
Request: add new

### ISSUE THREAD

**Issue by Roland80** [victorsolaya/Multiselect_Records_PCF#39]
I'm planning on using the PCF to allow adding of 'tags' to a record. The table in which the tags are stored is enabled for quick create and the PCF works fine, but when a tag can't be found, there's no way to add the tag as a new record.
It'd be a great addition if it were possible to enable the quick create so users can add new records (assuming their security role(s) allow this).

**Comment by victorsolaya** [comment]
Hi @Roland80  I will try to make something to improve this PCF with your feedback. Many thanks!
