### ISSUE TITLE
Is there version for On primes 

### ISSUE THREAD

**Issue by yassinsayed** [victorsolaya/Multiselect_Records_PCF#40]
Is there version for On primes

**Comment by victorsolaya** [comment]
Hello, at the moment there is no version for the on premises. Sorry for that

Enviado desde Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Yassin Sayed ***@***.***>
Enviado: Tuesday, January 10, 2023 4:07:07 PM
Para: victorsolaya/Multiselect_Records_PCF ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [victorsolaya/Multiselect_Records_PCF] Is there version for On primes (Issue #40)


Is there version for On primes
