### ISSUE TITLE
Duplicate Record Listed in the Dropdown

### ISSUE THREAD

**Issue by clarkcoleto** [victorsolaya/Multiselect_Records_PCF#41]
Hi can someone help me fix this, I don't know if it's something in my configuration or it's a bug. thanks!

Configuration:
![Screenshot 2023-01-18 104036](https://user-images.githubusercontent.com/122950870/213068768-9d3a3d29-e98a-461b-952d-8271ec7606aa.png)

Issue:
![image](https://user-images.githubusercontent.com/122950870/213068857-11612a5c-6576-4a08-9ad2-a7f12dc347c5.png)

**Comment by clarkcoleto** [comment]
maybe my question is that how can i filter the search to only show the active records ?

**Comment by clarkcoleto** [comment]
currently this is my filter

?$filter=contains(title, '{0}') or contains(keywords, '{0}') or contains(content, '{0}') or contains(description, '{0}') and statecode eq 3

**Comment by victorsolaya** [comment]
Hui @clarkcoleto  probably you need to add an statecode eq 0, because statecode, as this is a custom entity only has values to be 0 or 1. And the number 0 is active state
