### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by bakmichal** [victorsolaya/Multiselect_Records_PCF#42]
Hi! I have some error with field initialization. I tried using schema and logic name. Unfortunately I can't loading a multiple-choice field from your extension.  

![image](https://user-images.githubusercontent.com/126786935/222439349-5f878652-41d5-4c4d-82da-df18ee6bd970.png)
![image](https://user-images.githubusercontent.com/126786935/222439606-b80d815e-c0a8-4f98-86a0-8e01b7fe88e2.png)
![image](https://user-images.githubusercontent.com/126786935/222439680-37a25cce-6053-4d1b-a4e8-bfc3e5d59f4e.png)

**Comment by bakmichal** [comment]
[ErrorDetails (24).txt](https://github.com/victorsolaya/Multiselect_Records_PCF/files/10871881/ErrorDetails.24.txt)

**Comment by bakmichal** [comment]
[ErrorDetails.24.txt](https://github.com/victorsolaya/Multiselect_Records_PCF/files/10871887/ErrorDetails.24.txt)

**Comment by JasonClair** [comment]
I had the same issue. I had entered the Columns value incorrectly.

In my case I'd selected "new_name" but I needed to put "Name, new_name" for it work. Once I updated the column field & saved it worked ok.

**Comment by victorsolaya** [comment]
Hi @bakmichal  as @JasonClair  said it is because the columns, because you need to put the DisplayName, SchemaName so it can be shown in the Header Columns
