### ISSUE TITLE
Support for when record is not created yet

### ISSUE THREAD

**Issue by GoncaloFernandesDEV** [victorsolaya/Multiselect_Records_PCF#43]
When I'm creating a record and want to select child records from the pcf, based ona value from a lookup that is populated, the pcf can't find any records because it's trying to query the current parent record that doesn't exist yet, instead of retrieving the lookup value from the form

**Comment by victorsolaya** [comment]
Hi @GoncaloFernandesDEV , it is a good fit for an improvement. I will look into it
