### ISSUE TITLE
Can't test on Test environment

### ISSUE THREAD

**Issue by haprodeptrai123** [victorsolaya/Multiselect_Records_PCF#46]
I'm trying to show mock records in Test Environment. but it just keep showing this error : 
![image](https://github.com/victorsolaya/Multiselect_Records_PCF/assets/68005492/4142a992-5102-4890-9572-6cfe508b6bc8)
Thanks in advance for the guidance.

**Comment by victorsolaya** [comment]
Hi. I believe it is because you haven't set the correct columns. Read the guide so you can configure it correctly.
