### ISSUE TITLE
Field Filter Values on Create not working

### ISSUE THREAD

**Issue by mohsinonxrm** [victorsolaya/Multiselect_Records_PCF#47]
Hi,

First of all, thanks for providing this PCF control.

I'm using the latest version v1.0.0.13. 

I have a scenario where I need to use additional field filters so I've followed the documentation and added {1} {2} ... and provided the field names in the Field Filter Values (comma separated).

The problem is that on Create of a record (create form), it tries to filter the lookup, but since it is on Create (the record hasn't been saved yet), there's no GUID/id/PK yet for the PCF to query the value of the Field Filter Values to plug in the main $filter, and so it throws an error in the console.

this._entityRecordId is undefined at:

https://github.com/victorsolaya/Multiselect_Records_PCF/blob/5ddbcdb2f7d330956772ccd3738c0222cd9f01b4/MultiselectRecordsEntity/index.ts#L172

It works fine on the Update/Edit form, of course.

Can you please advise?

Thanks!

**Comment by mohsinonxrm** [comment]
@victorsolaya , FYI...

**Comment by victorsolaya** [comment]
Hi, you would need to perform something like a first save and then work with that.
