### ISSUE TITLE
List is showing blank result

### ISSUE THREAD

**Issue by abhiagra** [victorsolaya/Multiselect_Records_PCF#48]
Hi,

I load the control with default value, it shows the value in input field. However when I search, i see the data I get back from API but nothing is shown in UI.
I have verified that the response fields contains the props.column values along with atrributeid. What am I missing here?
Appreciate your help!

![image](https://github.com/victorsolaya/Multiselect_Records_PCF/assets/14907382/317f6c2b-ab91-4e8c-9466-07bf92a7f739)

**Comment by victorsolaya** [comment]
Hi, I believe you are missing something in the configuration of the control in the columns. Please refer to the documentation again.
