### ISSUE TITLE
Error loading control

### ISSUE THREAD

**Issue by irs250** [victorsolaya/Multiselect_Records_PCF#49]
@victorsolaya Thank you for making this PCF available! We have already been using it succesfully in our system for a while now. 

I am currenlty trying to configure the field on another entity (marketing emails in our dynamics marketing app), but I keep getting the error below.

<img width="200" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/f083caea-0449-4bd0-9434-e05459ec5519">

_"Error occured during initialization of control: vso_VictorSanchez.MultiselectRecordsEntity;Message: Cannot read properties of undefined (reading 'raw')"_

However, I don't know what I'm doing wrong. I am trying to create a multi-select look-up to the marketing list entity in our system. I believe I entered the correct values according to your documentation and how we configured it for other fields before. 

The marketing list table:
<img width="137" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/4be242f5-6b52-4124-aeb2-faab902419b8">

The primary column on the marketing list table:
<img width="324" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/aa71c987-73c4-4ae7-a27a-93fa1864dd3d">

What I configured on the single line of text field (max 4000 characters) I added to the marketing email entity:

<img width="237" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/cc8d5c8f-f5ed-4369-b96d-3b7270dfcf5f">

<img width="229" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/728b8635-f962-4700-973b-2085affd31f5">

<img width="234" alt="image" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/36992651/74a2cf4a-5158-49bb-aeb4-8c2644f9877e">

Am I missing something? Do you know what might be the issue?

Thanks!

**Comment by victorsolaya** [comment]
I believe the entityname is not list, it should have a prefix. Please, check your environment and get the correct schemaname for entity and fields
