### ISSUE TITLE
Only one contact is shown

### ISSUE THREAD

**Issue by mathiastornblom** [victorsolaya/Multiselect_Records_PCF#50]
Got the control to work but it only shows the first selected value (name). What is wrong?

**Comment by victorsolaya** [comment]
Hi,

Cant do much with that description. Can you show me the control properties
and the problem with some images?

**Comment by mathiastornblom** [comment]
<img width="565" alt="Screenshot 2024-07-01 at 07 22 58" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/15749388/917f0486-2514-43aa-9d90-6dc99067a715">
<img width="574" alt="Screenshot 2024-07-01 at 07 22 38" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/15749388/5510fd35-d325-4127-b53b-cbae4ced6084">
<img width="243" alt="Screenshot 2024-07-01 at 07 06 43" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/15749388/3b98296b-22b1-4a83-a977-b3eb0a14ecaf">
<img width="247" alt="Screenshot 2024-07-01 at 07 06 33" src="https://github.com/victorsolaya/Multiselect_Records_PCF/assets/15749388/e51c6a01-f666-482c-9765-5f57ad2f8269">

**Comment by victorsolaya** [comment]
At the momwnt, only weird thing I can see is the main attribute id, you
havr contactsid instead contactid, without the s, dont know if because the
language.
Could you try that?

I will try to check pcf on the new look as I havent done anything on it for
that.

**Comment by mathiastornblom** [comment]
Great spotted. That 's' made it work. So I guess it did not get the id and failed to generate the json in the field.
