### ISSUE TITLE
Control name is not appear in the solution / control sections

### ISSUE THREAD

**Issue by molyom** [victorsolaya/Multiselect_Records_PCF#6]
I've installed it but it has no name to be selected from controls Tab.
![image](https://user-images.githubusercontent.com/12083302/89020091-9fb2db80-d31e-11ea-94a3-7384ebd519aa.png)

**Comment by molyom** [comment]
Dear Victor, 
This behavior is saw for all of other Control (Form other developers) that I install in my instance. (all of my 6 instance) ... 
I thinks there is some update / Bug with Microsoft. I will write you again if there is any update.

**Comment by victorsolaya** [comment]
Hi! Many thanks for the update. I was looking for it but couldn't find anything yet.
