### ISSUE TITLE
the control does not work in "Offline Mode"

### ISSUE THREAD

**Issue by malkhawaja** [victorsolaya/Multiselect_Records_PCF#8]
Hi,
I noticed that the control does not retrieve records form the entity (which is enabled for offline mode and the records are available).
i am not sure if this is a bug or lack of functionality!

**Comment by victorsolaya** [comment]
Hi, thanks for sharing this.
I will check it and will come back to you. 
Right now I am using the xrm.webapi.retrieve... so probably I should look at using .webapi.offline method.

**Comment by malkhawaja** [comment]
Yes that could solve the issue... looking forward to the new version.

**Comment by victorsolaya** [comment]
Hi,

I have been cheching the PCF and played with the offline capabilities.
Could you let me know the query you are using in your filter?

I believe you are trying to use "contains" and this seems that is not supported by the offline webapi.
Please, look at this thread that's been opened as well https://github.com/MicrosoftDocs/dynamics-365-customer-engagement/issues/1916 refering to the same issue with the contains.

Could you try to use in your filter query an equals instead a contains, something similar to:
?$filter=firstname eq 'Firstname' 

I have tried that in my form and that seems to work, so it seems there is a limitation based on the queries.
