### ISSUE TITLE
Change code to React Hooks

### ISSUE THREAD

**Issue by victorsolaya** [victorsolaya/Multiselect_Records_PCF#9]
Code inside MultiselectRecords.tsx is using old version of React.
Looking forward to bringing some React Hooks inside this project.

**Comment by StellaJung-Student** [comment]
Hello, I would like to try this please let me know if it is ok~

**Comment by victorsolaya** [comment]
Hey!

Of course you can try. Your help will be really precious for that enhancement!

Thank you!

**Comment by StellaJung-Student** [comment]
Thank you~
Just wanted to ask, how I can run the code as a development mode like react-scripts~, I cannot run with npm run start or yarn start.
Can you provides the steps to run?

**Comment by victorsolaya** [comment]
This is a PCF (Power Component Framework) this works for Dynamics CRM.
I think you were thinking this is a react app, but it isn't, it is a piece of code for Dynamics CRM...
Sorry for not clarifying that.

**Comment by StellaJung-Student** [comment]
Hm I never heard about it. OK so can you add the instruction on Readme?

**Comment by victorsolaya** [comment]
It is harder than it what appears to be like. Microsoft Dynamics CRM is a platform in which you would need some "introduction". It is not as easy as doing a piece of code, it has its own interface and you need some experience with the platform.
If you want to know more, go and check what it is: https://dynamics.microsoft.com/en-us/crm/what-is-crm/
And if you want to try it just go for https://trials.dynamics.com/

But as I said, it is not some instructions, as you dont have any experience with the platform, you would need some guidance and introduction to this "world".

**Comment by victorsolaya** [comment]
Added some react hooks. Probably next version will force to have better hooks and better performance.
